version: '3'
services:
  app:
    build:
        context: ./
    tty: true
    volumes:
        - ./playwright_super_driver:/var/task
        - ./tmp:/user/download
    working_dir: /var/task
    environment:
      - USER_DOWNLOAD_DIR=/user/download/
      - WS_ENDPOINT=${WS_ENDPOINT:-ws://host.docker.internal:8080/ws}
      - PROXY_HOST=${PROXY_HOST:-}
      - PROXY_PORT=${PROXY_PORT:-}
      - PROXY_USER=${PROXY_USER:-}
      - PROXY_PASSWORD=${PROXY_PASSWORD:-}
